name = "TFG"
uuid = "428360d4-0b66-4714-8778-cc39d8d995c5"
authors = ["Juan Roman"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
